name: Build CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        id: get_hash
        run: echo "::set-output name=hash::$(git rev-parse --short ${{ github.sha }})"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ''

      - name: Set version
        run: |
          npm version --allow-same-version --no-git-tag-version ${{ steps.get_hash.outputs.hash }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ steps.get_hash.outputs.hash }}
          path: dist/