name: Build CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        id: get_hash
        run: echo "hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ''

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set version
        run: |
          VERSION=${{ env.hash }}
          jq '.version = "'"$VERSION"'"' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ env.hash }}
          path: dist/