name: Build CI
on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        run: echo "hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Set version
        run: |
          sudo apt-get install jq
          VERSION=${{ env.hash }}
          jq '.version = "commit-'"$VERSION"'"' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-ci-${{ env.hash }}
          path: dist/