name: Build Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: nyaa8/package-version@v1
        with:
          path: 'package.json'
          follow-symlinks: 'false'

      - name: Get version
        id: pv
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Zip dist
        run: |
          TAG_NAME=${{ steps.pv.outputs.current-version}}
          FILE_NAME=autopcr_web_vue-release_${TAG_NAME}.zip
          echo "filename=${FILE_NAME}" >> $GITHUB_ENV
          cd dist && zip -r ../${FILE_NAME} .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release-v${{ steps.pv.outputs.current-version}}
          tag_name: v${{ steps.pv.outputs.current-version}}
          files: ${{ env.filename }}
          generate_release_notes: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}